# main configuration file for all the amqp settings that the application will use
# defines the configuration for connections, channels, queues and exchanges as well as the dependencies for
# queues and exchanges
# for more informations please look at config/config_doc.yml, all configuration values are present there
amqp:
  baseConnection:
    live: &baseLive {}

  baseChannel:
    base: &baseChannQOS {count: 100, connection: live}

  baseExchange:
    base: &baseExchDurable {channel: live}

  baseQueue:
    base: &baseQueueDurable {channel: live}

  connection:
    live:
      <<:                   *baseLive

  channel:
    live:
      <<:                   *baseChannQOS

  exchange:
    testExchange:
      <<:                   *baseExchDurable
      name:                 {name: test-exchange}

  queue:
    testQueue:
      <<:                   *baseQueueDurable
      name:                 {name: test-queue}
      dependencies:
        exchange:
          - testExchange
      bindings:
          -
            exchange: test-exchange
            routingKey: example.test
    dateTimeQueue:
      <<:                   *baseQueueDurable
      name:                 {name: date-queue}
      dependencies:
        exchange:
          - testExchange
      bindings:
        -
          exchange: test-exchange
          routingKey: example.dateTime
